#!/bin/bash -eux
zero=$(readlink -f "$0")
zerodir="${zero%/*}"
export PATH="$zerodir:/usr/bin:/usr/sbin:/bin:/sbin"
InstallDesktop() {
    Quirks
    Desktop
    exit 0
}

Desktop() {
    DisableAccelerometerTilt
    # Minor glitch installing openoffice when default-jre was not already installed
    DEBIAN_FRONTEND=noninteractive aptitude install -y default-jre-headless
    local desktop_packages=(
	fonts-noto
	libvdpau-va-gl1
	lxqt
	openbox-lxde-session
	pavucontrol-qt
	vdpauinfo
	vlc
	xfce4-terminal
	xfwm4
	xfwm4-theme-breeze
	xserver-xorg-input-synaptics-hwe-18.04
    )
    DEBIAN_FRONTEND=noninteractive aptitude install -y "${desktop_packages[@]}"
    mkdir -p /etc/xdg/xdg-lxqt
    ln -snf /usr/share/lxqt /etc/xdg/xdg-lxqt
    # cp /usr/share/doc/avahi-daemon/examples/ssh.service /etc/avahi/services/
}

DisableAccelerometerTilt() {
    systemctl stop iio-sensor-proxy.service || :
    systemctl disable iio-sensor-proxy.server || :
    apt-get remove -y iio-sensor-proxy
}

InstallDesktop
