#!/bin/bash -eux
zero=$(readlink -f "$0")
zerodir="${zero%/*}"
export PATH="$zerodir:/usr/bin:/usr/sbin:/bin:/sbin"
InstallDevDesktop() {
    Desktop
    InstallDevTools
    InstallVMWareTools
    exit 0
}

InstallDevTools() {
    # Linters listed at http://www.flycheck.org/en/latest/languages.html
    local packages=(
	emacs25
	git
	groovy
	jsonlint
	python2.7
	python-flake8
	python3
	python3-flake8
	# Look at mypy
	rubocop
	shellcheck
	tidy
    )
    aptitude install -y "${packages[@]}"
}

InstallVMWareTools() {
    InstallOVFTool
    InstallPowerCLI
}

InstallOVFTool(){
    bash "$zerodir/blobs/VMware-ovftool-4.3.0-10104578-lin.x86_64.bundle" --eulas-agreed --console --required
}

InstallPowerCLI() {
    InstallPowerShell
    pwsh -c "Install-Module -Force -Name VMware.PowerCLI"
}

InstallPowerShell() {
    curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
    curl -o /etc/apt/sources.list.d/microsoft.list https://packages.microsoft.com/config/ubuntu/18.04/prod.list
    aptitude update
    DEBIAN_FRONTEND=noninteractive aptitude install -y powershell powershell-preview
}

InstallDevDesktop
