#!/bin/bash -eux
zero=$(readlink -f "$0")
zerodir="${zero%/*}"
export PATH="$zerodir:/usr/bin:/usr/sbin:/bin:/sbin"
InstallDevDesktop() {
    Desktop
    InstallDevTools
    exit 0
}

InstallDevTools() {
    # Linters listed at http://www.flycheck.org/en/latest/languages.html
    local packages=(
	emacs25
	git
	groovy
	jsonlint
	python2.7
	python-flake8
	python3
	python3-flake8
	# Look at mypy
	rubocop
	shellcheck
	tidy
    )
    aptitude install -y "${packages[@]}"
}

InstallDevDesktop
