#!/bin/bash -eux
zero=$(readlink -f "$0")
zerodir="${zero%/*}"
export PATH="$zerodir:/usr/bin:/usr/bin:/bin:/sbin"
InstallFamilyDesktop(){
    Desktop
    InstallGoogleChrome
    local packages=(
	libreoffice
    )
    DEBIAN_FRONTEND=noninteractive aptitude install -y "${packages[@]}"
    exit 0
}

InstallGoogleChrome() {
    curl -L https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
    cat > /etc/apt/sources.list.d/google-chrome.list <<EOF
deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
EOF
    apt-get update
    DEBIAN_FRONTEND=noninteractive aptitude install -y google-chrome-stable
}

InstallFamilyDesktop
